"""Measurement partition for the PMBM update step.

Wraps the clustering step and exposes a single ``partition()`` function
that converts a raw sensor point cloud into a list of ``MeasurementCell``
objects ready for consumption by the PMBM filter.

Relationship to PMBM
--------------------
In the PMBM framework each measurement cell Z_j is treated as the
complete set of measurements generated by exactly one target during
one scan. The partition step determines *how* raw points are grouped
before the probabilistic filter ever runs — it is a deterministic
pre-processing step, not part of the filter itself.

Choosing eps
------------
eps should be set to roughly the maximum intra-object point spacing
expected from the sensor. Typical values:

- Dense LiDAR (≥ 64-beam): 0.5 – 1.0 m
- Sparse LiDAR (16-beam) : 1.0 – 2.0 m
- Radar                  : 2.0 – 5.0 m (specular, sparse)
"""

from __future__ import annotations

import numpy as np

from .clustering import MeasurementCell, cluster_points


def partition(
    points: np.ndarray,
    eps: float,
    min_points: int = 1,
) -> list[MeasurementCell]:
    """Partition a sensor point cloud into PMBM measurement cells.

    Args:
        points:     Raw sensor points, shape (n, 2).
        eps:        Clustering radius in metres (see module docstring).
        min_points: Minimum points per cell; singletons are kept by
                    default (min_points=1) to allow Radar-sparse scenes.

    Returns:
        List of ``MeasurementCell`` objects, one per detected cluster.
        Empty list when the input contains no points.

    Example::

        cells = partition(lidar_scan, eps=1.0)
        for cell in cells:
            state = ggiw_update.update(predicted_state, cell.points)
    """
    clusters = cluster_points(points, eps=eps, min_points=min_points)
    return [MeasurementCell(c) for c in clusters]
